overrides:
  form-data@<2.5.4: '>=2.5.4'
  '@rolldown/pluginutils': 1.0.0-rc.9
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
  vitest: 4.1.11
  vite-plus: 0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
